// <auto-generated />
using System;
using AgendaBarber.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaBarber.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20261007213245_AgregarPerfilBarberia")]
    partial class AgregarPerfilBarberia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Barberia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("FotoActualizadaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("barberias", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Barbero", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BarberiaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.ToTable("barberos", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberiaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClienteTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("BarberiaId", "InicioUtc");

                    b.HasIndex("BarberoId", "InicioUtc");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.FotoBarberia", b =>
                {
                    b.Property<Guid>("BarberiaId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Datos")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("BarberiaId");

                    b.ToTable("fotos_barberia", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.HorarioTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Dia")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Fin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Inicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId", "Dia");

                    b.ToTable("horarios_trabajo", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BarberiaId")
                        .HasColumnType("uuid");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BarberiaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Barbero", b =>
                {
                    b.HasOne("AgendaBarber.Domain.Entities.Barberia", null)
                        .WithMany()
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Cita", b =>
                {
                    b.HasOne("AgendaBarber.Domain.Entities.Barberia", null)
                        .WithMany()
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaBarber.Domain.Entities.Barbero", null)
                        .WithMany()
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaBarber.Domain.Entities.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.FotoBarberia", b =>
                {
                    b.HasOne("AgendaBarber.Domain.Entities.Barberia", null)
                        .WithOne()
                        .HasForeignKey("AgendaBarber.Domain.Entities.FotoBarberia", "BarberiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.HorarioTrabajo", b =>
                {
                    b.HasOne("AgendaBarber.Domain.Entities.Barbero", null)
                        .WithMany("Horarios")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("AgendaBarber.Domain.Entities.Barberia", null)
                        .WithMany()
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AgendaBarber.Domain.Entities.Barberia", null)
                        .WithMany()
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgendaBarber.Domain.Entities.Barbero", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
